title: Jorge's Blog
author: Jorge Esparza
email: esparzacantero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A simple blog with an about me description, getting started on github pages.

# social links

github_username:  CodeSonder

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
